[package]

name = "hyperx"
version = "0.15.2" # don't forget to update html_root_url
description = "Hyper's typed header module, eXtracted and improved"
readme = "README.md"
documentation = "https://docs.rs/hyperx"
repository = "https://github.com/dekellum/hyperx"
license = "MIT"
authors = ["David Kellum <dek-oss@gravitext.com>"]
keywords = ["http", "hyper", "hyperium"]
categories = [
    "network-programming",
    "web-programming::http-client",
    "web-programming::http-server"
]
exclude = [
    ".gitignore",
    ".travis.yml",
    "appveyor.yml",
]
build = "build.rs"

[dependencies]
base64              = { version=">=0.10.1, <0.11" }
bytes               = { version=">=0.4.4, <0.5" }
http                = { version=">=0.1, <0.2", optional=true }
httparse            = { version=">=1.0, <1.4" }
language-tags       = { version=">=0.2, <0.3" }
log                 = { version=">=0.4, <0.5" }
mime                = { version=">=0.3.2, <0.4" }
percent-encoding    = { version=">=1.0, <1.1" }
time                = { version=">=0.1.37, <0.2" }
unicase             = { version=">=2.1.0, <2.6" }

# Unused, transitive constraints to preserve our MSRV
# cfg-if (via log) 0.1.10 release has MSRV 1.31.0
# alexcrichton/cfg-if@171ba7f
cfg-if              = { version=">=0.1.2, <0.1.10" }

[features]
default = [ "compat" ]
nightly = []
raw_status = []
compat = [ "http" ]
