[package]

name = "hyperx"
version = "0.16.0" # don't forget to update html_root_url
description = "Hyper's typed header module, eXtracted and improved"
readme = "README.md"
documentation = "https://docs.rs/hyperx"
repository = "https://github.com/dekellum/hyperx"
license = "MIT"
authors = ["David Kellum <dek-oss@gravitext.com>"]
keywords = ["http", "hyper", "hyperium"]
categories = [
    "network-programming",
    "web-programming::http-client",
    "web-programming::http-server"
]
exclude = [
    ".gitignore",
    ".travis.yml",
    "appveyor.yml",
]
build = "build.rs"

[dependencies]
base64              = { version=">=0.10.1, <0.12" }
bytes               = { version=">=0.4.4, <0.6" }
http                = { version=">=0.1, <0.2" }
httparse            = { version=">=1.0, <1.4" }
language-tags       = { version=">=0.2, <0.3" }
log                 = { version=">=0.4, <0.5" }
mime                = { version=">=0.3.2, <0.4" }
percent-encoding    = { version=">=2.1.0, <2.2" }
time                = { version=">=0.1.37, <0.2" }
unicase             = { version=">=2.1.0, <2.6" }

[features]
nightly = []
raw_status = []
compat = [] # no-op for backward compatibility
headers = []

[package.metadata.docs.rs]
features = ["headers"]
